#!/usr/bin/env python3
"""agentshive init — bootstrap the current directory for AgentsHive coordination.

Drops two files at the project root (or merges into existing):
  - AGENTS.md           Cross-tool agent rules (Zed, Codex CLI, Claude Code).
                        Tells every agent in this workspace how to assume a
                        role (Hivemind/Planner or Coder) and what AgentsHive
                        tools to use.
  - .zed/settings.json  Zed MCP server config so agents in the agent panel
                        auto-connect to AgentsHive for this project. Merged
                        into any existing settings.

Interactive — prompts for project slug, AgentsHive server URL, and API key.
Or pass them as flags for non-interactive use.

One-liner install (run from your project root):

    curl -fsSL https://raw.githubusercontent.com/Zecruu/ZecruAgentsHive/main/scripts/init_project.py | python -

Windows PowerShell:

    iwr -useb https://raw.githubusercontent.com/Zecruu/ZecruAgentsHive/main/scripts/init_project.py | python -

After init: open Zed in this dir. In the agent panel:
  - One thread: "You are the Hivemind for project <slug>. Read AGENTS.md."
  - Other threads: "You are a Coder for project <slug>. Read AGENTS.md."
The agents coordinate via AgentsHive MCP tools automatically.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

DEFAULT_SERVER = "https://agentshive-production.up.railway.app"
SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,62}$")

AGENTS_MD_TEMPLATE = """# AgentsHive coordination — `{slug}`

This project uses **AgentsHive** so multiple AI agents in this workspace coordinate via a shared MCP bridge instead of routing every decision through the human user.

> ℹ️ Generated by `scripts/init_project.py`. Edit freely — agents read what's here.

## Roles

When the user starts a new agent thread and says:

- **"You are the Hivemind"** (a.k.a. Planner) → you orchestrate. You don't write code.
- **"You are a Coder"** → you implement. You report to the Hivemind.

There is one Hivemind per project. You can have multiple Coders.

## Hivemind workflow

1. Talk with the user to understand what they want built.
2. Call `create_mission(brief)` once scope is clear. Brief must include: goal, acceptance criteria, constraints, definition of done.
3. Long-poll for Coder activity:
   - `wait_for_next_question(timeout=240)` → answer with `answer_question(question_id, response)`
   - `wait_for_next_summary(timeout=240)` → review with `respond_to_summary(summary_id, response)` or send fixes via `send_to_coder(message)`
4. `mark_mission_done(mission_id)` when complete.

Only ONE mission active at a time. Creating a new one supersedes the previous (it moves to `paused`).

## Coder workflow

1. Call `get_active_mission()` first. Read the brief.
2. Implement. **Don't ask the human user** for things the Hivemind can answer.
   - Stuck on requirements/design? → `ask_planner(question)` then `wait_for_answer(question_id, timeout=240)`
   - Genuinely need user-only info (credentials, personal preferences)? → ask the user directly.
3. At milestones: `submit_progress(summary, status)` where status is `in_progress`, `blocked`, or `done`. Then `wait_for_summary_response(summary_id, timeout=240)`.

## Multi-Coder

You can run multiple Coder threads on the same mission (e.g., one on frontend, one on backend, one on tests). They all see the same active mission via `get_active_mission()`. The Hivemind sees questions in arrival order — questions don't carry per-Coder identity in v1.x, so be clear about which part of the mission you're asking about.

Coordinate via the Hivemind. If you start work and find another Coder already has files locked, check in with the Hivemind via `send_to_planner(message)` to clarify scope.

## Project context

- **Slug**: `{slug}` — every agent MUST use this exact slug or their missions are invisible to each other.
- **Server**: `{server}`
- **MCP URL**: `{server}/mcp?project={slug}`

The Zed MCP server in `.zed/settings.json` is already wired to this URL.

## Full protocol reference

See the `agentshive` skill at `~/.claude/skills/agentshive/SKILL.md` (Claude Code) or fetch from NoticoMax cloud. It documents every tool, the mission lifecycle, and common gotchas.

## When NOT to use AgentsHive

- Trivial single-file edits — just do it.
- Read-only questions ("what does this file do?") — answer directly.
- Solo Claude/Codex session — AgentsHive only earns its keep when 2+ agents are coordinating.
"""

ZED_MCP_SERVER_KEY = "agentshive"


def _slug_from_cwd() -> str:
    name = Path.cwd().name.lower()
    name = re.sub(r"[^a-z0-9-]+", "-", name).strip("-")
    return name[:63] or "project"


def _prompt(label: str, default: str | None = None, hidden: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    if hidden:
        import getpass
        v = getpass.getpass(f"{label}{suffix}: ").strip()
    else:
        v = input(f"{label}{suffix}: ").strip()
    if not v and default is not None:
        return default
    return v


def _write_agents_md(target: Path, slug: str, server: str, force: bool) -> str:
    body = AGENTS_MD_TEMPLATE.format(slug=slug, server=server.rstrip("/"))
    if target.exists() and not force:
        existing = target.read_text(encoding="utf-8")
        if "AgentsHive coordination" in existing:
            return f"skip (AGENTS.md already mentions AgentsHive at {target})"
        # Append rather than overwrite — there may be other agent rules.
        sep = "\n\n---\n\n"
        target.write_text(existing.rstrip() + sep + body, encoding="utf-8")
        return f"appended to existing {target}"
    target.write_text(body, encoding="utf-8")
    return f"wrote {target}"


def _write_zed_settings(target: Path, slug: str, server: str, api_key: str) -> str:
    """Merge AgentsHive MCP config into .zed/settings.json (creates if missing).

    Zed's context_servers config format for HTTP MCP — preserves any existing
    servers and other settings. Key namespaced with project slug so multiple
    AgentsHive projects in one workspace don't collide.
    """
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists():
        try:
            data = json.loads(target.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            return f"skip ({target} exists but isn't valid JSON; merge manually)"
    else:
        data = {}

    servers = data.setdefault("context_servers", {})
    server_name = f"{ZED_MCP_SERVER_KEY}-{slug}"
    servers[server_name] = {
        "settings": {
            "url": f"{server.rstrip('/')}/mcp?project={slug}",
            "headers": {"Authorization": f"Bearer {api_key}"},
        }
    }
    target.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return f"wrote {target} (context_servers.{server_name})"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Bootstrap the current dir for AgentsHive multi-agent coordination."
    )
    parser.add_argument("slug", nargs="?", default=None,
                        help="Project slug (lowercase letters, digits, hyphens). "
                             "Defaults to current dir name.")
    parser.add_argument("--server", default=None,
                        help=f"AgentsHive server URL (default: {DEFAULT_SERVER}).")
    parser.add_argument("--key", default=None,
                        help="AgentsHive API key (else AGENTSHIVE_API_KEY env or prompt).")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite existing AGENTS.md instead of appending.")
    parser.add_argument("--no-zed", action="store_true",
                        help="Skip .zed/settings.json write (e.g., when not using Zed).")
    args = parser.parse_args()

    print("=== agentshive init ===")
    cwd = Path.cwd()
    print(f"Project dir: {cwd}")

    slug = args.slug or _prompt("Project slug", default=_slug_from_cwd())
    if not SLUG_RE.match(slug):
        print(f"ERROR: slug '{slug}' is invalid. Use lowercase letters, digits, hyphens; max 63 chars.",
              file=sys.stderr)
        return 2

    server = args.server or _prompt("AgentsHive server URL", default=DEFAULT_SERVER)
    api_key = (
        args.key
        or os.environ.get("AGENTSHIVE_API_KEY")
        or _prompt("AgentsHive API key", hidden=True)
    )
    if not api_key:
        print("ERROR: API key required (pass --key, set AGENTSHIVE_API_KEY env, or enter at prompt).",
              file=sys.stderr)
        return 2

    print()
    print(_write_agents_md(cwd / "AGENTS.md", slug, server, args.force))
    if not args.no_zed:
        print(_write_zed_settings(cwd / ".zed" / "settings.json", slug, server, api_key))
    print()
    print("=== Done. Next steps ===")
    print(f"1. Open this directory in Zed (or Claude Code, or Codex CLI).")
    print(f"2. New agent thread -> 'You are the Hivemind for project {slug}. Read AGENTS.md.'")
    print(f"3. New agent thread -> 'You are a Coder for project {slug}. Read AGENTS.md.'")
    print(f"4. The agents coordinate via AgentsHive MCP automatically.")
    print()
    print(f"Dashboard: {server.rstrip('/')}/dashboard")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
